### ISSUE TITLE
Quick looked at stampit usage

### ISSUE THREAD

**Issue by koresar** [jaysaurus/co-koa-core#4]
Hello.

The project looks great. I found there are fews trick which can be used (or not!) in your code base.

1) 
You have this stamp:
```js
const ClientConfig = stampit({
  props: {

    appKeys: null,
    <snip>
    useHBS: null

  },
  init ({

    appKeys = this.appKeys,
    <snip>
    root = this.root

 }) {

    this.appKeys = appKeys;
    <snip>
    this.root = root;

  }
});
```

To avoid this tripple copy&paste I'd recommend using the stamp I invented recently :))) - `ArgOverProp` - https://www.npmjs.com/package/@stamp/arg-over-prop

It will shorten your code, but will make is less explicit, which could be bad for some people, so think twice:
```js
const {argOverProp} = require('@stamp/arg-over-prop');

const ClientConfig = argOverProp({
  appKeys: null,
  <snip>
  useHBS: null
});
```

2) 
`co-koa-core` looks like a backend (node.js) project. I'd recommend using `@stamp/it` instead of `stampit`. There is a single reason - `@stamp/it` source code is [readable](https://github.com/stampit-org/stamp/blob/master/packages/it/index.js) (not minified).

Have fun!

**Comment by jaysaurus** [comment]
hello! Thank you for the kind words :) I will most definitely investigate this asap!

best
Jay

**Comment by koresar** [comment]
1. The `stampit` and `@stamp/it` have identical API. So, you just replace one module with another. So, no refactoring at all.
I wrote 1 minute text about them here: https://medium.com/@koresar/fun-with-stamps-episode-20-stampit-v4-9a043a36a984

2. Very valid. I'd do the same.

You have asked about how to do private (privileged) data in JS. Well, this is a general JS question. Actually, you already doing it okay. Let me list few other ways.

1. I'd just do it with less code:
```js
const SomeObject = stampit.init(function (secret) {
  function doSomethingSecret () {
     ... secret ...
  }

  this.getASecret = function() {
    const revelation = doSomethingSecret();
    ...
  }
});
```

2. Another way to do it is via Symbols.
```js
const secretData = new Symbol();
const secretMethod = new Symbol();

const SomeObject = stampit({
  init (secret) { this[secretData] = secret; } ),
  props: {
    [secretMethod] () {
      return this[secretData];
    }
  },
  methods: {
    getASecret () {
      const revelation = this[secretMethod]();
      ...
    }
  }
});
```

3. Third method is to use `WeakMap`: http://fitzgeraldnick.com/2014/01/13/hiding-implementation-details-with-e6-weakmaps.html
```js
const storageOfPrivates = new WeakMap();

const SomeObject = stampit({
  init (secret) {
    storageOfPrivates.set(this, { 
      secret,
      doSomethingSecret () {
        return this.secret;
      }
    });
  },
  methods: {
    getASecret () {
      const myPrivates = storageOfPrivates.get(this);
      const revelation = myPrivates.doSomethingSecret();
      ...
    }
});
```

4. Since all the `@stamp/*` modules are compatible with both `stampit` and `@stamp/it` you can use this stamp https://www.npmjs.com/package/@stamp/privatize
I wrote briefly about it here: https://medium.com/@koresar/fun-with-stamps-episode-15-the-stamp-modules-ecosystem-a296d15be599
Warning! This will hide **all** the properties of an object instance. Meaning that if you compose this stamp with another stamp both will have all properties hidden behind the proxy object.
```js
import Privatize from '@stamp/privatize';

const SomeObject = stampit(Privatize.privatizeMethods('doSomethingSecret'), {
  init (secret) { this.secret = secret; },
  methods: {
    doSomethingSecret() { return this.secret; },
    getASecret () {
      const revelation = this.doSomethingSecret();
      ...
    }
  }
});
```
Both `.secret` and `.doSomethingSecret()` are private here.

Hope that helps.

**Comment by jaysaurus** [comment]
nice! thanks! I'll definitely give these serious consideration next time I get a chance to do some work on the core :)

**Comment by jaysaurus** [comment]
Oh good grief! talk about not seeing the wood for the trees!! Yes, I see what you mean now; you're (quite rightly) inserting a classical function as a callback for stampit to execute *face palm*... I've been up to my eyeballs in all the engineering of the project I didn't stop to see the obvious! Thanks for giving me a programmatic slap across the chops ;) yeah i'll tweak that when I get a free afternoon!

I'll probably use `arg-over-prop` too thinking about it...
